### ISSUE TITLE
ask for utils.snippets utils.SimCLS

### ISSUE THREAD

**Issue by yiy1x** [Jeryi-Sun/Law-Match-SIGIR-23#1]
你好！我是一名研0的学生（纯新手），我在尝试复现你的代码时遇到了一些问题。我注意到缺少了utils包中的utils.snippets和utils.SimCLS文件。非常抱歉打扰你，但我想问一下，是否可能向我提供这两个文件呢？

**Comment by Jeryi-Sun** [comment]
utils.SimCLS  无用可以删除，utils.snippets已上传，调试一下可以运行
